'''
This example config file shows some of the different use cases of kmm.
See documentation for full list of options
Rename this folder to config to use this file
'''


user: <your_username/email_here>
password: <your_password_here>
komga_url: <your_komga_server_url_here>


# Collection Catagories are used to set prefix
# and determine location of poster art and overlays 
collection_categories : 
  General      : '{0}: '
  Series Group : '{1}: '
  Characters   : '{2}: '
  Teams        : '{3}: '
  Universe     : '{4}: '
  Creators     : '{5}: '
  Events       : '{6}: '
  DC Group     : '{7.1}: '
  Marvel Group : '{7.2}: '
  Publishers   : '{8}: '
  Ages         : '{9}: '



smart_collections : 

# This will create a collection called {0}: Manga
# with all series with reading direction set to right to left 
  - collection_name: Manga
    collection_category: General
    search_params:
      search: reading_direction:right_to_left

# This will create a collection called {1}: Hellboy
# with all series returned from search for 'Hellboy' 
  - collection_name: Hellboy
    collection_category: Series Group

# This will create a collection called {2}: Nightwing
# with all series returned from search for 'Nightwing' 
  - collection_name: Nightwing
    collection_category: Characters

# This will create a collection called {1}: Terminator
# with all series returned from search for 'Terminator',
# except with series that include 'Deathstroke' or 'X-Terminators'
  - collection_name: Terminator
    collection_category: Series Group
    search_params: 
      search: '"Terminator" NOT ("Deathstroke" OR "X-Terminators")'

# This will create a collection called {8}: Image
# with all series from publisher 'Image',
  - collection_name: Image
    collection_category: Publishers
    search_params:
      publisher: Image

# This will create a collection called {5}: Jack Kirby
# with all series with Jack Kirby as penciller or writer,
  - collection_name: Jack Kirby
    collection_category: Creators
    search_params:
      search: '((penciller:(Jack Kirby)) OR (writer:(Jack Kirby)))'

# This will create a collection called {5}: Alan Moore
# with all series with Alan Moore as writer,
  - collection_name: Alan Moore
    collection_category: Creators
    search_params:
      author: Alan Moore, writer 


readlist_categories :
  General         : '{0}: '

  DC Complete     : '{1.0}: '
  DC Eras         : '{1.1}: '  
  DC Characters   : '{1.2}: '
  DC Teams        : '{1.3}: '
  DC Universe     : '{1.4}: '
  DC Events       : '{1.5}: '
  DC Creator Runs : '{1.6}: '
  
  Marvel Complete     : '{2.0}: '
  Marvel Eras         : '{2.1}: '  
  Marvel Characters   : '{2.2}: '
  Marvel Teams        : '{2.3}: '
  Marvel Universe     : '{2.4}: '
  Marvel Events       : '{2.5}: '
  Marvel Creator Runs : '{2.6}: '

  Indie Complete     : '{3.0}: '
  Indie Era          : '{3.1}: '  
  Indie Characters   : '{3.2}: '
  Indie Teams        : '{3.3}: '
  Indie Universe     : '{3.4}: '
  Indie Events       : '{3.5}: '
  Indie Creator Runs : '{3.6}: '


smart_readlists :

  # This will create a readlist with the name {3}: 'Justice League: New 52'
  # from a cbl file located in the assets/cbl directory
  # Any current readlist with the name {3}: 'Justice League: New 52' will be overwritten
  # cbl should match exact name of cbl file with or without file extension
  # Books will be matched against the cbl file and unmatched books will be skipped
  # If all books skipped no readlist will be made
  # Poster art and overlay will be looked for in assets/readlists/Teams
  - readlist_name: 'Justice League: New 52'
    readlist_category: DC Teams
    cbl: Justice League 006 (New 52)

  # More info can be output on each unmatched by adding display_unmatched: True
  - readlist_name: 'Justice League: Rebirth'
    readlist_category: DC Teams
    cbl: Justice League 007 (Rebirth)
    display_unmatched: True

  # Readlists can be grabbed from web pages that display raw text of the cbl file
  # Tested with cbl files from https://github.com/DieselTech/CBL-ReadingLists

  - readlist_name: 'Batman: Night of the Owls'
    readlist_category: DC Events
    cbl: 'https://raw.githubusercontent.com/DieselTech/CBL-ReadingLists/main/DC/Events/unsorted/1%20-%20New%2052/DC65%20-%20Night%20of%20the%20Owls.cbl'

