'''
This example config file shows some of the different use cases of kmm.
See documentation for full list of options
Rename this folder to config to use this file
'''


user: <your_username/email_here>
password: <your_password_here>
komga_url: <your_komga_server_url_here>


# Collection Catagories are used to set prefix
# and determine location of poster art and overlays 
collection_catagories : 
  General      : '{0}: '
  Series Group : '{1}: '
  Characters   : '{2}: '
  Teams        : '{3}: '
  Universe     : '{4}: '
  Creators     : '{5}: '
  Events       : '{6}: '
  DC Group     : '{7.1}: '
  Marvel Group : '{7.2}: '
  Publishers   : '{8}: '
  Ages         : '{9}: '



smart_collections : 

# This will create a collection called {0}: Manga
# with all series with reading direction set to right to left 
  - collection_name: Manga
    collection_catagory: General
    search_params:
      search: reading_direction:right_to_left

# This will create a collection called {1}: Hellboy
# with all series returned from search for 'Hellboy' 
  - collection_name: Hellboy
    collection_catagory: Series Group

# This will create a collection called {2}: Nightwing
# with all series returned from search for 'Nightwing' 
  - collection_name: Nightwing
    collection_catagory: Characters

# This will create a collection called {1}: Terminator
# with all series returned from search for 'Terminator',
# except with series that include 'Deathstroke' or 'X-Terminators'
  - collection_name: Terminator
    collection_catagory: Series Group
    search_params: 
      search: '"Terminator" NOT ("Deathstroke" OR "X-Terminators")'

# This will create a collection called {8}: Image
# with all series from publisher 'Image',
  - collection_name: Image
    collection_catagory: Publishers
    search_params:
      publisher: Image

# This will create a collection called {5}: Jack Kirby
# with all series with Jack Kirby as penciller or writer,
  - collection_name: Jack Kirby
    collection_catagory: Creators
    search_params:
      search: '((penciller:(Jack Kirby)) OR (writer:(Jack Kirby)))'

# This will create a collection called {5}: Jack Kirby
# with all series with Alan Moore as writer,
  - collection_name: Alan Moore
    collection_catagory: Creators
    search_params:
      author: Alan Moore, writer 


readlist_catagories :
  General      : '{0}: '
  Series Group : '{1}: '
  Characters   : '{2}: '
  Teams        : '{3}: '
  Universe     : '{4}: '
  Creators     : '{5}: '
  Events       : '{6}: '
  DC Era       : '{7.1}: '
  Marvel Era   : '{7.2}: '
  Publishers   : '{8}: '
  Ages         : '{9}: '


smart_readlists :
  # This will create a readlist with the name {3}: 'Justice League: New 52'
  # from a cbl file located in the assets/cbl directory
  # Any current readlist with the name {3}: 'Justice League: New 52' will be overwritten
  # cbl should match exact name of cbl file with or without file extension
  # Books will be matched against the cbl file and unmatched books will be skipped
  # If all books skipped no readlist will be made
  # (Second Example) More info can be output on each unmatched by adding display_unmatched: True
  # Poster art and overlay will be looked for in assets/readlists/Teams

  - readlist_name: 'Justice League: New 52'
    readlist_catagory: Teams
    cbl: Justice League 006 (New 52)

  - readlist_name: 'Justice League: Rebirth'
    readlist_catagory: Teams
    cbl: Justice League 007 (Rebirth)
    display_unmatched: True



